version: '3.8'

services:
  backendpython:
    build:
      context: ./backendpython
      dockerfile: Dockerfile
    container_name: sibud_backendpython
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - backendjava  

  backendjava:
    build:
      context: ./backendjava
      dockerfile: Dockerfile
    container_name: sibud_backendjava
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./data:/app/data
